swagger: "2.0"
info:
  title: User Service
  description: Service to perform CRUD operations using goa
  version: ""
host: localhost:8080
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /:
    get:
      tags:
      - user
      summary: list user
      description: List all users
      operationId: user#list
      responses:
        "200":
          description: OK response.
          schema:
            type: array
            items:
              $ref: '#/definitions/StoredUserResponse'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/UserListDbErrorResponseBody'
      schemes:
      - http
    post:
      tags:
      - user
      summary: add user
      description: Add new user and return its ID.
      operationId: user#add
      parameters:
      - name: AddRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/UserAddRequestBody'
      responses:
        "201":
          description: Created response.
          schema:
            $ref: '#/definitions/UserAddResponseBody'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/UserAddDbErrorResponseBody'
      schemes:
      - http
  /openapi.json:
    get:
      tags:
      - user
      summary: Download ./gen/http/openapi.json
      operationId: user#/openapi.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
definitions:
  StoredUserResponse:
    title: 'Mediatype identifier: application/vnd.cellar.stored-user; view=default'
    type: object
    properties:
      id:
        type: integer
        description: ID is the unique id of the blog.
        example: 5515246943780495549
        format: int64
      name:
        type: string
        description: Name of person
        example: hes
        maxLength: 100
    description: A StoredUser describes a user retrieved by the storage service. (default
      view)
    example:
      id: 11281141276310197849
      name: sub
    required:
    - id
    - name
  UserAddDbErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Unable to process db request (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  UserAddRequestBody:
    title: UserAddRequestBody
    type: object
    properties:
      id:
        type: integer
        description: ID of a user
        example: 9592574435837841775
        format: int64
      name:
        type: string
        description: Name of person
        example: 3d1
        maxLength: 100
    example:
      id: 2118306210829482107
      name: h07
  UserAddResponseBody:
    title: UserAddResponseBody
    type: object
    properties:
      id:
        type: integer
        description: ID of a user
        example: 13906744339640640010
        format: int64
      name:
        type: string
        description: Name of person
        example: lhf
        maxLength: 100
    example:
      id: 15797882809909419288
      name: oy8
  UserListDbErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Unable to process db request (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
